#!/bin/bash
# NEXUS OS - Master Compiler Script (Production Fixed)

echo "🚀 Initiating Nexus OS Compilation Matrix..."

# 1. Prepare Repositories
echo "🌐 Ensuring repositories are active..."
sudo apt-get update
sudo apt-get install -y software-properties-common
sudo add-apt-repository -y universe
sudo apt-get update

# 2. Install live-build and utilities
echo "📦 Installing live-build toolchain and Debian keyrings..."
sudo apt-get install -y live-build xorriso squashfs-tools debian-archive-keyring

# 3. Clean up old environments
echo "🧹 Wiping old build data..."
sudo lb clean --purge

# 4. Configure Linux Base Engine with Absolute Mirror Overrides
echo "⚙️ Configuring Linux Base Engine..."
lb config -d bookworm \
  --mirror-bootstrap "http://deb.debian.org/debian/" \
  --mirror-chroot "http://deb.debian.org/debian/" \
  --mirror-binary "http://deb.debian.org/debian/" \
  --archive-areas "main contrib non-free non-free-firmware" \
  --binary-images iso-hybrid

# 5. Define Package Installation Staging List
echo "📦 Staging Nexus packages..."
mkdir -p config/package-lists
cat <<EOF > config/package-lists/nexus.list.chroot
live-boot
live-config
systemd
xserver-xorg
xinit
wayland-protocols
python3
python3-pip
python3-pyqt5
python3-requests
chromium
thunar
git
curl
wget
nano
htop
EOF

# 6. Inject Your Custom System Core Files
echo "🧬 Injecting Nexus UI and AI Daemon into the core..."
mkdir -p config/includes.chroot/
cp -r rootfs/. config/includes.chroot/

# 7. Force the Boot Override Hook
echo "🔒 Writing boot sequence override..."
mkdir -p config/hooks/normal
cat <<EOF > config/hooks/normal/01-enable-nexus-service.hook.chroot
#!/bin/sh
systemctl enable nexus-ui.service
EOF
chmod +x config/hooks/normal/01-enable-nexus-service.hook.chroot

# 8. Compile the Live OS Distribution
echo "🔥 Compiling bare-metal .ISO file. Please hold..."
sudo lb build

# 9. Verify and Rename Output (Robust Name Catcher Fix)
echo "🔍 Searching for compiled system image media..."
if [ -f live-image-amd64.hybrid.iso ]; then
    mv live-image-amd64.hybrid.iso nexus_os_v1.iso
    echo "✅ SUCCESS: nexus_os_v1.iso is ready for launch!"
elif [ -f live-image-amd64.iso ]; then
    mv live-image-amd64.iso nexus_os_v1.iso
    echo "✅ SUCCESS: nexus_os_v1.iso is ready for launch!"
else
    echo "❌ Build failed. Code compiled but no core .ISO image was generated by live-build."
    exit 1
fi